using DevExpress.DataAccess.Sql;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace TestTask
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            sqlDataSource1.FillAsync();
        }

        private void BuildFilterstring()
        {
            string flterStr = "";
            DateTime dateAndTime;
            if (comboBoxEdit1.EditValue != null)
            {
                flterStr = "[NazwaLokalu]='" + comboBoxEdit1.EditValue.ToString() +"'";
            };

            if (comboBoxEdit2.EditValue != null)
            {
                dateAndTime = (DateTime)comboBoxEdit2.EditValue;
                if (flterStr != "")
                {
                    flterStr = flterStr + " and [DataEksportu]>=#" + dateAndTime.ToString("MM-dd-yyyy") + "#";
                } else
                {
                    flterStr = "[DataEksportu]>=#" + dateAndTime.ToString("MM-dd-yyyy") + "#";
                }
            };

            if (comboBoxEdit3.EditValue != null)
            {
                dateAndTime = (DateTime)comboBoxEdit3.EditValue;
                if (flterStr != "")
                {
                    flterStr = flterStr + " and [DataEksportu]<=#" + dateAndTime.ToString("MM-dd-yyyy") + "#";
                }
                else
                {
                    flterStr = "[DataEksportu]<=#" + dateAndTime.ToString("MM-dd-yyyy") + "#";
                }
            };

            sqlDataSource1.ClearRows();
            SelectQuery selectQuery = (SelectQuery)sqlDataSource1.Queries[0];
            selectQuery.FilterString = flterStr;
            sqlDataSource1.FillAsync();
        }

        private void comboBoxEdit1_SelectedValueChanged(object sender, EventArgs e)
        {
            BuildFilterstring();
        }

        private void comboBoxEdit2_EditValueChanged(object sender, EventArgs e)
        {
            BuildFilterstring();
        }

        private void comboBoxEdit3_EditValueChanged(object sender, EventArgs e)
        {
            BuildFilterstring();
        }
    }
}
